image: Visual Studio 2017
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
nuget:
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  project: Snowplow.Analytics.sln
  verbosity: minimal
test_script:
- cmd: >-
    dotnet test Snowplow.Analytics.Tests/Snowplow.Analytics.Tests.csproj

    dotnet pack Snowplow.Analytics/Snowplow.Analytics.csproj --configuration Release
artifacts:
- path: Snowplow.Analytics/bin/RELEASE/Snowplow.Analytics.*.nupkg
deploy:
- provider: NuGet
  api_key:
    # NUGET_API_KEY
    secure: fkik3XGPWwOjxaLG1W/cPSPU2tGlfo6E3E+sQPsAPOzXq92WlaNrHawiKbN8JfOa
  on:
    appveyor_repo_tag: true